# Generated by Django 4.2.6 on 2023-10-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
